#!/usr/bin/bash
# set -x
prefix="https://www.youtube.com/watch_videos?video_ids="
format=""
input=""
temp=
count=0

if [[ -p /dev/stdin ]]; then
	input=($(cat -))
fi
while [[ "${1,,}" =~ --.* ]]; do

	if [[ "$1" == "--" ]]; then
		break
	fi

	if [[ "${1,,}" =~ --remove && "$2" != "" ]]; then
		remove=$(echo "$2" | sed 's/^\s*$/0/' | bc)
		shift 2
		continue
	fi

	if [[ "${1,,}" =~ --copy ]]; then
		copy=true
		shift 1
		continue
	fi

	if [[ "${1,,}" =~ --(f|first-)?log && "$2" != "" ]]; then
		flog=$(realpath "$2")
		[[ -d $flog ]] && { flog=$flog/$(basename "$0").txt; }
		shift 2
		continue
	fi

	if [[ "${1,,}" =~ --read && ! $watch ]]; then
		read=true
		shift 1
		continue
	fi

	if [[ "${1,,}" =~ --watch && ! $read ]]; then
		watch=true
		shift 1
		continue
	fi

	break
done

if [[ $read ]]; then
	temp=
	echo -n "> " >&2
	while read item && [ -n "$item" ]; do
		echo -n "> " >&2
		temp+="\n$item"
	done
	temp=${temp//\\n/ }
	input_term="${temp:1}"
fi

if [[ $watch ]]; then
	temp=
	continue=true
	trap 'continue=false' INT
	echo -ne "[OPTION] Press Ctrl+C to stop watching.\n" >&2
	while [[ $continue == "true" ]]; do
		watch -gtn.1 'xclip -o -selection clipboard' >/dev/null
		if [[ $continue == "true" ]]; then
			item="$(xclip -o -selection clipboard)"
			echo -e "> $item" >&2
			temp+="\n$item"
		fi
	done
	echo >&2
	temp=${temp//\\n/ }
	input_term="${temp:1}"
	trap - INT
fi

input=(${input[@]} $input_term $@)
[[ -v flog && -a "$flog" ]] && { input=("${input[@]}" $(cat "$flog")); }
for argu in "${input[@]}"; do
	fargu=($(echo -e "${argu//\\}"))
	for entry in "${fargu[@]}"; do
		format=$(echo "$format$([[ $format == "" ]] && echo -n || echo ,)""$(echo "$entry" | sed -E "s/^.+(v=|.be\/|video_ids=)([^&]*).*/\2/g")")
	done
	
done

read -ra splitstr <<< $(
	IFS=',' read -ra out <<< "$format"
	echo "${out[@]}"
)
# splitstr=($(IFS=',' read -reA <<< "$format"))
[[ -v remove ]] && { echo "[OPTION]:Removing $remove video(s)..." >&2; }
splitstr=(${splitstr[@]:$remove})
outstr=
selection=

if [ ${#splitstr[@]} -gt 50 ]; then
	echo -e "${#splitstr[@]} entries, splitting...\n" >&2
	while true; do
		outstr=$(echo "${splitstr[@]:$((count*50)):50}" | sed 's/ /,/g')
		if [[ $outstr ]]; then
			echo "[$((count+1))]" >&2
			echo "$prefix$outstr"
			[[ $selection ]] && { selection+="\n"; }
			selection+="$prefix$outstr"
		else
			break
		fi

		count=$((count+1))
	done
	
	[[ $copy ]] && { echo -e "\n[OPTION]:Copying..." >&2; echo -e "$selection" | sed '2,$s/^/\n/' | xclip -selection clip -rmlastnl; }
	[[ -v flog ]] && { echo -e "[OPTION]:Logging to $flog" >&2; echo -e "$selection" | sed '2,$s/^/\n/' > "$flog"; }
else
	outstr=$(echo -e "${splitstr[@]}" | sed 's/ /,/g')
	echo -e "${#splitstr[@]} entries total.\n" >&2
	echo "$prefix$outstr"
	[[ $copy ]] && { echo -e "\n[OPTION]:Copying..." >&2; echo -e "$prefix$outstr" | sed '2,$s/^/\n/' | xclip -selection clip -rmlastnl; }
	[[ -v flog ]] && { echo -e "[OPTION]:Logging to $flog" >&2; echo -e "$prefix$outstr" > "$flog"; }
fi
exit 0
