#!/usr/bin/bash
prefix="https://www.youtube.com/watch_videos?video_ids="
format=""
input=""
temp=
count=0

if [ -p /dev/stdin ]; then
	input=($(cat -))
fi
while
[[ "$(echo "$1" | tr '[:upper:]' '[:lower:]')" == "--remove" && $2 != "" ]] ||
[[ "$(echo "$1" | tr '[:upper:]' '[:lower:]')" == "--copy" ]] ||
[[ "$(echo "$1" | tr '[:upper:]' '[:lower:]')" == "--read" && ! $watch ]] ||
[[ "$(echo "$1" | tr '[:upper:]' '[:lower:]')" == "--watch" && ! $read ]] ||
[[ "$(echo "$1" | tr '[:upper:]' '[:lower:]')" == "--log" && $2 != "" ]]; do

	if [[ "$(echo "$1" | tr '[:upper:]' '[:lower:]')" == "--remove" && $2 != "" ]]; then
		remove=$(echo "$2" | sed 's/^\s*$/0/' | bc)
		shift 2
	fi

	if [[ "$(echo "$1" | tr '[:upper:]' '[:lower:]')" == "--copy" ]]; then
		copy=true
		shift 1
	fi

	if [[ "$(echo "$1" | tr '[:upper:]' '[:lower:]')" == "--read" && ! $watch ]]; then
		read=true
		shift 1
	fi

	if [[ "$(echo "$1" | tr '[:upper:]' '[:lower:]')" == "--log" && $2 != "" ]]; then
		log=$(realpath "$2")
		[[ -d $log ]] && { log=$log/$(basename "$0").txt; }
		shift 2
	fi

	if [[ "$(echo "$1" | tr '[:upper:]' '[:lower:]')" == "--watch" && ! $read ]]; then
		watch=true
		
		shift 1
	fi

done

if [[ $read ]]; then
	echo -n "> " >&2
	while read item && [ -n "$item" ]; do
		echo -n "> " >&2
		input_term+="\n$item"
	done
	temp=${input_term//\\n/ }
	input_term="${temp:1}"
fi

if [[ $watch ]]; then
	trap 'continue=false' INT
	continue=true
	echo -ne "[OPTION] Press Ctrl+C to stop watching.\n" >&2
	while [[ $continue == "true" ]]; do
		watch -gtn.1 'xclip -o -selection clipboard' >/dev/null
		if [[ $continue == "true" ]]; then
			item="$(xclip -o -selection clipboard)"
			echo -e "> $item" >&2
			input_term+="\n$item"
		fi
	done
	echo >&2
	temp=${input_term//\\n/ }
	input_term="${temp:1}"
	trap - INT
fi

input=(${input[@]} $input_term $@)
[[ -v log ]] && { input=("${input[@]}" $(cat "$log")); }
for argu in "${input[@]}"; do
	fargu=($(echo -e "${argu//\\}"))
	for entry in "${fargu[@]}"; do
		format=$(echo "$format$([[ $format == "" ]] && echo -n || echo ,)""$(echo "$entry" | sed -E "s/^.+(v=|.be\/|video_ids=)([^&]*).*/\2/g")")
	done
	
done

read -ra splitstr <<< $(
	IFS=',' read -ra out <<< "$format"
	echo "${out[@]}"
)
# splitstr=($(IFS=',' read -reA <<< "$format"))
[[ -v remove ]] && { echo "[OPTION]:Removing $remove video(s)..." >&2; }
splitstr=(${splitstr[@]:$remove})
outstr=
selection=

if [ ${#splitstr[@]} -gt 50 ]; then
	echo -e "${#splitstr[@]} entries, splitting...\n" >&2
	while true; do
		outstr=$(echo "${splitstr[@]:$((count*50)):50}" | sed 's/ /,/g')
		if [[ $outstr ]]; then
			echo "[$((count+1))]" >&2
			echo "$prefix$outstr"
			[[ $selection ]] && { selection+="\n"; }
			selection+="$prefix$outstr"
		else
			break
		fi

		count=$((count+1))
	done
	
	[[ $copy ]] && { echo -e "\n[OPTION]:Copying..." >&2; echo -e "$selection" | sed '2,$s/^/\n/' | xclip -selection clip -rmlastnl; }
	[[ -v log ]] && { echo -e "[OPTION]:Logging to $log" >&2; echo -e "$selection" | sed '2,$s/^/\n/' > "$log"; }
else
	outstr=$(echo -e "${splitstr[@]}" | sed 's/ /,/g')
	echo -e "${#splitstr[@]} entries total.\n" >&2
	echo "$prefix$outstr"
	[[ $copy ]] && { echo -e "\n[OPTION]:Copying..." >&2; echo -e "$prefix$outstr" | sed '2,$s/^/\n/' | xclip -selection clip -rmlastnl; }
	[[ -v log ]] && { echo -e "[OPTION]:Logging to $log" >&2; echo -e "$prefix$outstr" > "$log"; }
fi
exit 0
